# Generated by Django 3.1.6 on 2021-02-16 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecash',
            name='currency_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_currency', to='cash_register.currencydenomination', unique=True),
        ),
    ]
