# Generated by Django 3.1.6 on 2021-02-16 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0002_auto_20210216_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecash',
            name='currency_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='available_currency', to='cash_register.currencydenomination'),
        ),
    ]
