# Generated by Django 3.1.6 on 2021-02-16 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0003_auto_20210216_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecash',
            name='currency_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='available_currency', to='cash_register.currencydenomination', to_field='currency_type'),
        ),
        migrations.AlterField(
            model_name='paymentform',
            name='currency_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_currency', to='cash_register.currencydenomination', to_field='currency_type'),
        ),
    ]
