# Generated by Django 3.1.6 on 2021-02-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0004_auto_20210216_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentform',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
